library(ggplot2)
tiff("optimized_tissue_sig_deg_scz_front_lzw.tiff",width=1400,height=1400,units="px",res=300,compression = 'lzw')
df <- read.table("E:\\000research\\000eqtl_transcript_gwas\\MCGA_result\\Revised_eLife\\MCGA_vs_SPrediXcan\\MCGA_SPrediXcan.txt",sep="\t",head=F)
df$V1 <- factor(df$V1,levels = unique(df$V1),order=T)
df$V2 <- factor(df$V2,levels = unique(df$V2),order=T)
col <- c('#348498','#004d61','#ff502f')
p <- ggplot(data = df, aes(x = V1, y = V3, fill = V2)) + geom_bar(stat = 'identity', position = 'dodge')+labs(x = "", y = "Significant gene count")+theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.text = element_text(size=10),axis.title = element_text(size=10),axis.text.x = element_text(angle = 70,hjust=1,vjust = 1),legend.text=element_text(size=6),panel.background = element_blank())+scale_fill_manual(values = col)+guides(fill=guide_legend(title=''))
p+theme(legend.key.size = unit(0.4,"line"))
dev.off()
